{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": ,
   "id": "547c31b0-cea4-4fa3-9615-b876f4d42510",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%writefile streamlit_app.py\n",
    "\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.impute import SimpleImputer \n",
    "from compose import ColumnTransformer\n",
    "import cloudpickle\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.tree import DecisionTreeClassifier\n",
    "from sklearn.esemble import RandomFrosetClassifier\n",
    "\n",
    "@st.cache_resource\n",
    "def load_preprocessor():\n",
    "    with open(\"preprocessor.bin\", 'rb') as f:\n",
    "        preprocessor = cloudpickle.load(f)\n",
    "    print(\"Successfully loaded preprocessor\")\n",
    "    return preprocessor\n",
    "\n",
    "@st.cache_resource\n",
    "def load_model():\n",
    "    with open(\"model.bin\", 'rb') as f:\n",
    "        model = cloudpickle.load(f)\n",
    "    print(\"Loaded model Successfully\")\n",
    "    return model \n",
    "\n",
    "\n",
    "preprocessor = load_preprocessor()\n",
    "model = load_model()\n",
    "\n",
    "\n",
    "\n",
    "def clearn_data(x):\n",
    "    try:\n",
    "        x = x.copy()\n",
    "        if x['SeniorCitizen'].dtype != 'O':\n",
    "            x['SeniorCitizen'] = x['SeniorCitizen'].astype('str')\n",
    "            print('Converted SeniorCitizen data type to string')\n",
    "        else:\n",
    "            print('SeniorCitizen data type is already string')\n",
    "\n",
    "        if x['TotalCharge'].dtype == 'O':\n",
    "            x['TotalCharge'] = x['TotalCharge'].replace(' ', None).astype('float')\n",
    "            print('Converted TotalCharge data type to float')\n",
    "        else:\n",
    "            print('TotalCharge data type is not string.Hence not converting it')\n",
    "\n",
    "        if 'customerID' in x.cloumns:\n",
    "            x.drop(columns=['customerID'], inplace=True)\n",
    "            print('Dropped customerID column')\n",
    "       else:\n",
    "            print('customerID columns not found. Hence, not deleting it')\n",
    "\n",
    "       print(\"Data Clearing Successful\")\n",
    "       return None\n",
    "\n",
    "def preprocess_inference_data(x_test, y_test, preprocessor):\n",
    "    try:\n",
    "        x_test = x_test.copy()\n",
    "        if y_test is not None:\n",
    "            y_test = y_test.copy()\n",
    "\n",
    "        (categorical_mode_imputer_ct,\n",
    "         one_hot_encoder_ct,\n",
    "         numeric_median_imputer_ct,\n",
    "         minmax_scaler, label_encoder) = preprocessor\n",
    "\n",
    "        # Categorical missing value imputation\n",
    "        categorical_mode_imputer_ct.set_output(transform='pandas')\n",
    "        x_test = categorical_mode_imputer_ct.transform(x_test)\n",
    "      \n",
    "        # Onehot encoder\n",
    "        one_hot_encoder_ct.set_output(transform='pandas')\n",
    "        x_test = one_hot_encoder_ct.transform(x_test)\n",
    "\n",
    "        # numeric missing value imputation\n",
    "        numeric_median_imputer_ct.set_output(transform='pandas')\n",
    "        x_test = numeric_median_imputer_ct.transform(x_test)\n",
    "\n",
    "        # minmax scaler\n",
    "        x_test = pd.DataFrame(minmax_scaler.transform(x_test), columns=minmax_scaler.get_feature_names_out())\n",
    "\n",
    "        # Label encoder\n",
    "        if y_test is not None:\n",
    "           y_test = label_encoder.transform(y_test)\n",
    "\n",
    "        print('Successfully Preprocessed Data')\n",
    "        return x_test, y_test, label_encoder           \n",
    "    except Exception as e:\n",
    "        print(f\"Failed To Preprocess Data: {e}')\n",
    "        return "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
